### ISSUE TITLE
Feature Request - personal VAR from scenes / looks

### ISSUE THREAD

**Issue by VAM-Kitten** [feelfar/varManager#19]
Hi Feelfar!

I have been using your VarManager (now version 1.0.4.6) for a very long time and I can't imagine working without it.

If it is okay, I would like to request a new feature.

I have many, many VAR files and 80% of them are not needed. But some of them are just big packs with everything in them.

Your option "Saves JsonFile" scans files in Save folder for dependencies and create symbolic links of needed VARS from repository folder. But it links entire VARS, that are sometimes very big.

I need an option to scan Save files (scenes and looks, but I am more interested in looks) and extract only needed files to a separate folder and create a new VAR from them. And of course replace all references in source json files to point to files in that new VAR. Keeping directory structure of original VARS.

Here is a little video I made for you, to make it easier to understand what I mean:

[YOUTUBE VIDEO](https://www.youtube.com/watch?v=qnn8u9bv8r8)

Please note that this video is not real, it is only a visualization how I see that feature implemented.

Do you think it would be possible to code such a feature into one of the future versions of your VarManager? I know it would be a hard work and it would take a long time. 

I've tried to do it with macros, but there is a problem with .VAM and .WMI files.
.VAM files contain additional references to .JPG .VAB and .VAJ files within the same folder.
The same is with .WMI files - they point to .VMB files.
I have no idea how to add such references with a simple script, that's why I need help.

Thank you for everything you do for VAM community!

Keep up the good work!
VK

**Comment by feelfar** [comment]
Poor English, I will reply in Chinese and machine-turned English together。

谢谢你的建议，我也一样在烦心这个问题，一堆的var文件不需要和重复的数据太多了，但版本和依赖问题使得精简很难有大效果，我也在考虑如何对这些var文件进行有效精简，当然由于涉及改动var文件，可能要很慎重才会加入这功能。

Thank you for your suggestion, I am also as annoyed with this problem, a bunch of var files do not need and duplicate too much data, but version and dependency issues make it difficult to streamline the effect, I am also considering how to effectively streamline these var files.because it involves changing the var files data，may have to be very careful before adding this feature.

**Comment by VAM-Kitten** [comment]
I know it would cause some problems, but it is a sacrifice I am willing to take :) Also, I've been doing it all manually and it worked correctly.

So what I did, I just listed all files in the JSON (scene,look), found them in different VARS, extracted them, preserving the original directory structure, packed them into a new VAR, replaced all the references in JSON file to point to that new VAR, and it worked. As I mentioned, in .VAM and .WMI files there are additional references, so I had to copy them to a new VAR also, for it to work.

May be if should be a separate tool?

Of may be, for the start, a separate button would make a TXT file that would list all files needed for the scene to work, without copying anything and without making a new VAR? I would make one myself.

Of course such VARs would be for private use only, not for distribution. Just to get rid of not needed files and speed-up VAM.

**Comment by wdch771** [comment]
> 

I think it may be possible to provide a function of scanning presets, whether they are plugin presets, clothing presets, or scene presets, etc., and then store them in the database, and add a column of markers to the var package list to display, so that We can know that this var package is not only depended on by other var packages, but also by presets. This is just my opinion.

**Comment by VAM-Kitten** [comment]
I wrote a script in Powershell that does exactly what I wanted. The script works perfectly with your VarManager. Now I can build local, personalized VARs without worrying about both the performance of VAM itself and storage space.

So it is time to close this thread.
